# Generated by Django 4.1.1 on 2022-10-02 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppCoder", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estudiante",
            name="apellido",
        ),
    ]
